# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejc', '0002_comunidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='comunidade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ejc.Comunidade'),
        ),
    ]
