# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejc', '0003_inscricao_comunidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='ds_comunidade',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
