# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejc', '0004_inscricao_ds_comunidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='celular',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='telefone',
            field=models.CharField(max_length=14),
        ),
    ]
