# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejc', '0005_auto_20170315_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='nome_padrinho',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='padrinho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='telefone_padrinho',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
