# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejc', '0008_auto_20170316_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='padrinho',
            field=models.BooleanField(choices=[(1, 'Sim'), (2, 'Não')], default=2),
        ),
    ]
