# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejc', '0009_auto_20170316_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='padrinho',
        ),
    ]
