# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejc', '0012_auto_20170318_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
