# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejc', '0013_auto_20170318_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='endereco',
            field=models.CharField(default='', max_length=200),
        ),
    ]
