# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ejc', '0015_auto_20170320_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenador',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='coordenador',
            name='servo',
        ),
        migrations.RemoveField(
            model_name='coordenador',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Encontro',
        ),
        migrations.RemoveField(
            model_name='servo',
            name='comunidade',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_alteracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='usuario_alteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Coordenador',
        ),
        migrations.DeleteModel(
            name='Equipe',
        ),
        migrations.DeleteModel(
            name='Servo',
        ),
    ]
