# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 11:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ejc', '0016_auto_20170323_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Encontro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('telefone', models.CharField(blank=True, max_length=14, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('outra_comunidade', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('comunidade', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ejc.Comunidade')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejc.Equipe')),
            ],
        ),
        migrations.AddField(
            model_name='coordenador',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejc.Equipe'),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='servo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejc.Servo'),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
