# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejc', '0019_auto_20170406_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenador',
            name='servo',
        ),
    ]
