# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejc', '0020_remove_coordenador_servo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servo',
            name='coordenador',
            field=models.BooleanField(default=False),
        ),
    ]
